#!/bin/bash
echo ""
echo ""
			   php -S 127.0.0.1:4444 > /dev/null 2>&1 &


start() {
echo -e " "
rm -rf lhrlife
echo -e ""
	echo -e "\n"
	echo -e ""
sleep 1 && ssh -R 80:localhost:4444 nokey@localhost.run > lhrlife 2>&1 &
echo ""
	sleep 12
	llink=$(cat lhrlife | grep -o 'https://[0-9a-zA-Z.]*.lhr.life')
	
}

start

echo -e "\e[96m=======================\e[92m   SUMAN © 2022 FF  \e[96m=======================\e[92m"
                           echo -e " "
			   echo -e " "
                           echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > >\e[0m'
                           printf "\e[1;33m\e[0m\e[1;33m LocalXpose Link :\e[0m\e[1;77m %s\e[0m\n" $llink                               
                           echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > > >\e[0m'
			   echo ""
			   echo ""
			   echo -e "\e[96m=========================\e[92m Online Hacking \e[96m========================= \e[93m" 
                           echo ""
